<table id="management_register_report" class="table table-hover nowrap">
    <thead>
        <tr>
            <th>#</th>
            <th>idcard</th>
            <th>hn</th>
            <th>refno</th>
            <th>มีขั้นตอนทำประวัติ</th>
            <th>มีคิวทำประวัติ</th>
            <th>ประเภทคิว</th>
            <th>คิว</th>
            <th>ถูกเรียกหรือไม่</th>
            <th>เวลาเรียกครั้งแรก</th>
            <th>เวลาเรียกครั้งสุดท้าย</th>
            <th>userที่เรียก</th>
            <th>counterที่เรียก</th>
            <th>ถูกholdหรือไม่</th>
            <th>เวลาที่hold</th>
            <th>ข้อความhold</th>
            <th>userที่hold</th>
            <th>เสร็จสิ้น</th>
            <th>เวลาเสร็จสิ้น</th>
            <th>userเสร็จสิ้น</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($Data) && count($Data) > 0) :
            foreach ($Data as $key => $value) {
        ?>
                <tr>
                    <td><?=$key+1;?></td>
                    <td><?=$value->idcard;?></td>
                    <td><?=$value->hn;?></td>
                    <td><?=$value->refno;?></td>
                    <td><?=$value->selectqueue?'ใช่':'ไม่ใช่';?></td>
                    <td><?=$value->queue_exist?'ใช่':'ไม่ใช่';?></td>
                    <td><?=$value->queuetype;?></td>
                    <td><?=$value->queueno;?></td>
                    <td><?=$value->queue_called?'ใช่':'ไม่ใช่';?></td>
                    <td><?=$value->first_called;?></td>
                    <td><?=$value->last_called;?></td>
                    <td><?=$value->calluser;?></td>
                    <td><?=$value->callcounter;?></td>
                    <td><?=$value->queue_hold?'ใช่':'ไม่ใช่';?></td>
                    <td><?=$value->hold_when;?></td>
                    <td><?=$value->hold_message;?></td>
                    <td><?=$value->hold_user;?></td>
                    <td><?=$value->closequeue?'ใช่':'ไม่ใช่';?></td>
                    <td><?=$value->closequeue;?></td>
                    <td><?=$value->closeuser;?></td>
                </tr>
        <?php
            }
        endif;
        ?>
    </tbody>
</table>